/// Flutter icons SolfyIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SolfyIcons
///      fonts:
///       - asset: fonts/SolfyIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

/// Иконки солфи
class SolfyIcons {
  SolfyIcons._();

  static const _kFontFam = 'SolfyIcons';
  static const String? _kFontPkg = null;

  static const IconData arrow = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData category___rocket =
      IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData category___smile =
      IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checkmark = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData document = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filters = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fingerprint =
      IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fire = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow2 = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData market = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData network = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData news_feed = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pen = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData question = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scan_card = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData find = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shops = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData solfy_smile =
      IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData telephone = IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData time = IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData touchid = IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder = IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData geo_1 = IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_up = IconData(0xe851, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_down =
      IconData(0xe852, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe855, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData balance = IconData(0xe856, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData geolocation =
      IconData(0xe857, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData geo = IconData(0xe858, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sad_solfy = IconData(0xe859, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData geo_solfy = IconData(0xe85a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData happy_solfy =
      IconData(0xe85b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock = IconData(0xe85c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info_thick =
      IconData(0xe85d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info_inverted =
      IconData(0xe85e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_long =
      IconData(0xe85f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info = IconData(0xe860, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData push_notification =
      IconData(0xe861, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cam = IconData(0xe862, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData face_id = IconData(0xe863, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
